# Generated by Django 3.0 on 2022-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
